-- INSERT INTO DBO.ORDERS (ORDERID,CUSTOMERID,ORDER_DATE) VALUES
-- ('101','1','2024-04-12'),
-- ('102','1','2024-03-12'),
-- ('103','2','2024-04-05'),
-- ('104','3','2024-04-09'),
-- ('105','4','2024-03-23')


-- WITH CTE_SINGLE_CUST AS(
-- SELECT CUSTOMERID FROM DBO.ORDERS GROUP BY CUSTOMERID HAVING COUNT(*) = 1
-- )
-- SELECT C.CUSTOMERID,C.ORDER_DATE FROM DBO.ORDERS C INNER JOIN CTE_SINGLE_CUST  CS 
-- ON C.CustomerID = CS.CUSTOMERID 
-- WHERE MONTH(C.ORDER_DATE) = 4



-- SELECT * FROM DBO.ORDERS 
-- WHERE CUSTOMERID 
-- IN (SELECT CUSTOMERID FROM DBO.ORDERS GROUP BY CustomerID HAVING COUNT(*) = 1)
-- AND MONTH(ORDER_DATE) = 4

-- CREATE VIEW `ORDER` AS
-- SELECT * FROM DBO.ORDERS;


SELECT * FROM `order`;
